### ISSUE TITLE
Fix installation instructions

### ISSUE THREAD

**Issue by nohwnd** [keenethics/neutral-icon-theme#1]
The installation instructions say that the icon theme will show up as `Neutral` but it shows up as 
![image](https://user-images.githubusercontent.com/5735905/50513671-86d6aa00-0a99-11e9-88c5-7c2e912744dc.png)
Please fix either the naming or the installation instructions.

**Comment by rationalquality** [comment]
I added a clearer description of the installation process. Thanks for pointing this problem
