### ISSUE TITLE
Allow for `"hidesExplorerArrows": true`

### ISSUE THREAD

**Issue by oscarmcm** [keenethics/neutral-icon-theme#3]
Is there any way to hide the arrow in the folder icons? 

See https://github.com/Microsoft/vscode/issues/25655

**Comment by rationalquality** [comment]
Thank for issue. I'll think about it after add open folder icon

**Comment by rationalquality** [comment]
@oscarmcm, I'm just hiding the arrows

**Comment by oscarmcm** [comment]
@usernamus thanks!!  👍
